title: "piClinic"
logo: "/images/TermFront-piclinic_sm.jpg"
email: bobw@piclinic.org
description: > # this means to ignore newlines until "baseurl:"
  Affordable patient-record automation for limited-resource clinics.<br>
baseurl: "" # the subpath of your site
url: "https://piclinic.org" # the base hostname & protocol for where the content is h
twitter_username: bobwatsonphd
google_analytics: UA-58134115-3
github_username:  rbwatson
include: ['pages']
author:
  name: Bob Watson
  url: https://docsbydesign.com
theme: jekyll-theme-slate
